/*
 * File created on Mar 12, 2019
 *
 * Copyright (c) 2019 Carl Harris, Jr
 * and others as noted
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.soulwing.s2ks.aws;

import java.security.Key;
import java.util.Arrays;
import javax.crypto.spec.SecretKeySpec;

import org.soulwing.s2ks.base.EncryptionKey;

/**
 * An {@link EncryptionKey} that was generated by the AWS KMS.
 *
 * @author Carl Harris
 */
class KmsEncryptionKey implements EncryptionKey {

  static final String ALGORITHM = "AES";

  private final byte[] plainText;
  private final byte[] cipherText;
  private final String masterKeyId;

  KmsEncryptionKey(byte[] plainText, byte[] cipherText,
      String masterKeyId) {
    this.plainText = plainText;
    this.cipherText = cipherText;
    this.masterKeyId = masterKeyId;
  }

  @Override
  public Key getKey() {
    return new SecretKeySpec(plainText, ALGORITHM);
  }

  @Override
  public byte[] getCipherText() {
    return cipherText;
  }

  @Override
  public String getMasterKeyId() {
    return masterKeyId;
  }

  @Override
  public void destroy() {
    Arrays.fill(plainText, (byte) 0);
  }

}
